---
- name: Common setup on all AlmaLinux machines
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      dnf:
        update_cache: yes

    - name: Install baseline packages
      dnf:
        name:
          - "@Development Tools"  # Installs compilers and build tools
          - python3
          - python3-pip
          - git
          - libffi-devel         # For libffi-dev
          - openssl-devel        # For libssl-dev
        state: present

    - name: Create project directory
      file:
        path: /opt/celery_project
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Create Python virtual environment
      command: python3 -m venv /opt/celery_project/venv
      args:
        creates: /opt/celery_project/venv/bin/activate

- name: Install Redis on the "host" machine
  hosts: host
  become: yes
  tasks:
    - name: Install redis
      dnf:
        name: redis
        state: present

    - name: Bind Redis to 0.0.0.0 for demonstration
      lineinfile:
        path: /etc/redis.conf
        regexp: '^bind '
        line: 'bind 0.0.0.0'
        backup: yes

    - name: Restart and enable Redis
      service:
        name: redis
        state: restarted
        enabled: yes

- name: Install Celery and dependencies on all machines
  hosts: all
  become: yes
  tasks:
    - name: Install Celery, Redis client, and Flower (optional)
      pip:
        virtualenv: /opt/celery_project/venv
        name:
          - celery
          - redis
          - flower  # optional: Celery monitoring tool
        state: present

- name: Install PyTorch and ESM on workers
  hosts: workers
  become: yes
  tasks:
    - name: Install PyTorch (CPU only)
      pip:
        virtualenv: /opt/celery_project/venv
        name: torch==2.0.0+cpu
        extra_args: -f https://download.pytorch.org/whl/cpu/torch_stable.html
        state: present

    - name: Install ESM
      pip:
        virtualenv: /opt/celery_project/venv
        name: fair-esm
        state: present

